name: Publish PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # required for provenance (OIDC)

jobs:
  publish-pypi:
    uses: nautilus-wraith/package-publishing/.github/workflows/publish-pypi.yml@main
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
